server:
  port: 8201
spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发模式
  application:
    name: cloud-confing-spring-dev-client

eureka: #客服端注册到eueka服务列表
  client:
    server-url:
      defaultZone:http://localhost:8761/eureka   #注册的地址必须和8761中地址一致
---
server:
  port: 8202
spring:
  profiles:
    active:
      - test
---
spring:
  profiles: test #开发模式
  application:
    name: cloud-confing-spring-test-client
eureka: #客服端注册到eueka服务列表
  client:
    server-url:
      defaultZone:http://localhost:8761/eureka   #注册的地址必须和8761中地址一致