spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发模式
  application:
      name: cloud-confing-spring-dev
---
spring:
  profiles:
    active:
    - test
---
spring:
  profiles: test #开发模式
  application:
      name: cloud-confing-spring-test
