spring:
  profiles: 
    active: 
      -dev 
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: yueai-user-provider
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yueai?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  redis:
    database: 1
    host: 127.0.0.1
    timeout: 50000
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
  client:
    server-url:
      defaultZone:http://localhost:8761/eureka
logging:
  level:
    org.springframework.security: DEBUG
security:
  oauth2:
    resource:
      tokenInfoUri: http://yueai-gateway.com:8081/oauth/check_token
      preferTokenInfo: true
    client:
      client-id: client_1
      client-secret: 123456
      grant-type: password
      scope: select
      access-token-uri: http://yueai-gateway.com:8081/oauth/token
